# Generated by Django 5.1.15 on 2026-09-26 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_category_alter_product_options'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_zone', models.ForeignKey(db_column='from_zone_id', on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_transfers', to='warehouse.location')),
                ('responsible_user', models.ForeignKey(blank=True, db_column='responsible_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_zone', models.ForeignKey(db_column='to_zone_id', on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_transfers', to='warehouse.location')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Internal Transfer',
                'verbose_name_plural': 'Internal Transfers',
                'db_table': 'internal_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approved_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transferred_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit_of_measure', models.CharField(blank=True, default='Units', max_length=50)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_location', models.ForeignKey(blank=True, db_column='destination_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_transfer_items', to='warehouse.location')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='products.product')),
                ('source_location', models.ForeignKey(blank=True, db_column='source_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transfer_items', to='warehouse.location')),
                ('transfer', models.ForeignKey(db_column='transfer_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.internaltransfer')),
            ],
            options={
                'verbose_name': 'Internal Transfer Item',
                'verbose_name_plural': 'Internal Transfer Items',
                'db_table': 'internal_transfer_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_type', models.CharField(default='INTERNAL_TRANSFER', max_length=50)),
                ('reference_type', models.CharField(default='INTERNAL_TRANSFER', max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(blank=True, db_column='destination_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='warehouse.location')),
                ('performed_by', models.ForeignKey(blank=True, db_column='performed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('source_location', models.ForeignKey(blank=True, db_column='source_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='warehouse.location')),
                ('transfer_item', models.ForeignKey(blank=True, db_column='transfer_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='operations.internaltransferitem')),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='internaltransfer',
            index=models.Index(fields=['transfer_number'], name='internal_tr_transfe_3fbf60_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransfer',
            index=models.Index(fields=['status'], name='internal_tr_status_cc42cb_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransfer',
            index=models.Index(fields=['scheduled_date'], name='internal_tr_schedul_c95951_idx'),
        ),
        migrations.AddIndex(
            model_name='internaltransfer',
            index=models.Index(fields=['created_at'], name='internal_tr_created_ecedb9_idx'),
        ),
    ]
