# Generated by Django 6.1.1 on 2026-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('warehouse', models.CharField(default='Central Hub (WH-01)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
